import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { ReactNode } from "react";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Hangyul Yi | Portfolio",
  description: "Generated by create next app",
  icons: {
    icon: [
      {
        media: '(prefers-color-scheme: light)',
        url: '/favicon-light.ico',
        href: '/favicon-light.ico',
      },
      {
        media: '(prefers-color-scheme: dark)',
        url: '/favicon-dark.ico',
        href: '/favicon-dark.ico',
      },
    ]
  }
};

const Layout = ({ children }: { children: React.ReactNode }) => {
  return (
    <html>
      <body>
        { children }
      </body>
    </html>
  )
}

export default Layout;
